-- Enterprise Application — 初始化迁移
-- 与 JPA ddl-auto=update 配合，确保表结构完整

CREATE TABLE IF NOT EXISTS enterprise (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(128) NOT NULL UNIQUE,
    credit_code VARCHAR(64),
    area VARCHAR(64),
    industry VARCHAR(64),
    scale VARCHAR(64),
    legal_representative VARCHAR(64),
    contact_name VARCHAR(64),
    contact_phone VARCHAR(32),
    address VARCHAR(255),
    registered_capital BIGINT,
    established_date VARCHAR(255),
    annual_revenue BIGINT,
    revenue_growth_rate DOUBLE,
    rd_investment BIGINT,
    rd_ratio DOUBLE,
    debt_ratio DOUBLE,
    net_profit BIGINT,
    employees INT,
    rd_staff_count INT,
    rd_staff_ratio DOUBLE,
    patent_count INT,
    market_share DOUBLE,
    tags VARCHAR(255),
    inventory_status VARCHAR(32) DEFAULT '在库',
    status VARCHAR(32) DEFAULT 'NORMAL',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS declaration (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    enterprise_id BIGINT NOT NULL,
    enterprise_name VARCHAR(128),
    type VARCHAR(32) NOT NULL COMMENT 'INNOVATIVE/PROVINCIAL/XIAOJUREN',
    level VARCHAR(32),
    category VARCHAR(32),
    year INT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    submit_time DATETIME,
    declaration_code VARCHAR(32),
    revenue BIGINT,
    rd_investment BIGINT,
    rd_ratio DOUBLE DEFAULT 0,
    debt_ratio DOUBLE DEFAULT 0,
    patent_count INT DEFAULT 0,
    market_share DOUBLE DEFAULT 0,
    product_name VARCHAR(128),
    product_market_share DOUBLE DEFAULT 0,
    chain_description TEXT,
    material_completeness INT DEFAULT 0,
    ai_suggestions TEXT,
    ai_issues TEXT,
    ai_passed_items TEXT,
    ai_missing_items TEXT,
    review_comment VARCHAR(512),
    reviewer_id BIGINT,
    review_time DATETIME,
    market_years INT,
    equity_financing2y DOUBLE,
    net_profit DOUBLE,
    main_revenue DOUBLE,
    main_revenue_ratio DOUBLE,
    revenue_growth2y_avg DOUBLE,
    market_years_score INT,
    lead_product_domain VARCHAR(255),
    digital_level INT,
    net_profit_rate DOUBLE,
    quality_award_provincial BIT,
    quality_iso BIT,
    quality_brand BIT,
    quality_standard BIT,
    digital_score INT,
    quality_score INT,
    refined_score INT,
    feature_key_industry BIT,
    feature_special_tech BIT,
    feature_first_set BIT,
    feature_green_mfg BIT,
    feature_chuangke BIT,
    feature_design_award BIT,
    talent_national BIT,
    talent_provincial BIT,
    talent_city BIT,
    talent_recommend BIT,
    feature_score INT,
    ip_high_value INT,
    ip_class1_self INT,
    ip_class1 INT,
    ip_class2 INT,
    rd_staff_ratio DOUBLE,
    rd_institution_level VARCHAR(32),
    ip_score INT,
    rd_score INT,
    innovation_score_detail INT,
    direct_tech_award BIT,
    direct_national_award BIT,
    direct_chuangke BIT,
    total_score INT,
    professional_score INT,
    declaration_eligible BIT,
    eligible_reason VARCHAR(255),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_decl_enterprise (enterprise_id),
    INDEX idx_decl_status (status),
    INDEX idx_decl_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS declaration_material (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    declaration_id BIGINT NOT NULL,
    group_name VARCHAR(64) NOT NULL,
    name VARCHAR(255),
    document_id BIGINT,
    status VARCHAR(32) DEFAULT 'MISSING',
    identify_result TEXT,
    required INT DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_dm_declaration (declaration_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    enterprise_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(64),
    file_url VARCHAR(512),
    file_name VARCHAR(255),
    file_size BIGINT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_doc_enterprise (enterprise_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
